"""
Django settings for draco project.

Generated by 'django-admin startproject' using Django 2.0.9.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
from urllib.parse import urljoin

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '%q1zi1$62$5tlnye+w=m)0j!w2x=r*#**d0(a-)h-gh^ppcilw'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '192.168.8.214']


# Application definition

INSTALLED_APPS = [
    # 'dracoin.apps.DracoinConfig',
    'tinymce',
    'dracoin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'draco.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates/')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'draco.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGES = [
    ('en', ('English')),
]

LANGUAGE_CODE = 'en-GB'

TIME_ZONE = 'Europe/Kiev'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static/')]

# Mediafiles (Images, etc.)
MEDIA_ROOT = os.path.join(BASE_DIR, 'upload/')
MEDIA_URL = '/upload/'


# TinyMCE configuration
TINYMCE_DEFAULT_CONFIG = {
    # 'selector': '#admin textarea', # chose form selector to personalise configuration
    'selector': 'textarea.admin', # chose form selector to personalise configuration
    'language': 'en-GB',
    'language_url': urljoin(STATIC_URL, 'languages/en_GB.js'),
    # 'language': 'uk',
    # 'language_url': urljoin(STATIC_URL, 'languages/uk.js'),
    # 'language_url': '../../../../static/languages/uk.js',
    # 'language_url': os.path.join(BASE_DIR, 'static/languages/uk.js'),
    # 'language': 'ru',
    # 'language_url': urljoin(STATIC_URL, 'languages/ru.js'),
    'content_css': 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css',
    'height': 360,
    'plugins': [
      'autosave advlist autolink link image lists charmap print preview hr anchor pagebreak \
      searchreplace wordcount visualblocks visualchars code fullscreen \
      insertdatetime media nonbreaking save table contextmenu directionality emoticons \
      paste codesample help',
    ],
    'inline': False,
    'contextmenu': 'link anchor image',
    'menubar': 'file edit insert view format table help',
    'statusbar': True,
    'toolbar1': 'alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | searchreplace visualblocks fullscreen preview code',
    'toolbar2': 'bold italic underline | link anchor image blockquote charmap hr codesample',
    'codesample_languages': [
        {'text': 'C-like', 'value': 'clike'},
        {'text': 'C++', 'value': 'cpp'},
        {'text': 'Makefile', 'value': 'makefile'},
        {'text': 'Python', 'value': 'python'},
        {'text': 'Django/Jinja2', 'value': 'django'},
        {'text': 'Haskell', 'value': 'haskell'},
        {'text': 'SQL', 'value': 'sql'},
        {'text': 'JSON+JSONP', 'value': 'json'},
        {'text': 'HTML/XML', 'value': 'html'},
        {'text': 'CSS', 'value': 'css'},
        {'text': 'JavaScript', 'value': 'javascript'},
        {'text': 'Diff', 'value': 'diff'},
        {'text': 'Docker', 'value': 'docker'},
        {'text': 'Git', 'value': 'git'},
        {'text': 'Markdown', 'value': 'markdown'},
        {'text': 'LaTeX', 'value': 'latex'},
        {'text': 'Arduino', 'value': 'arduino'},
    ],
    # 'selector': 'textarea.user', # chose form selector to personalise configuration
    # 'content_css': 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css',
    # 'height': 200,
    # 'plugins': [
    #   'autosave advlist autolink link lists charmap preview wordcount insertdatetime emoticons paste codesample',
    # ],
    # 'contextmenu': False,
    # 'menubar': False,
    # 'statusbar': True,
    # 'toolbar': 'insertfile undo redo | bold italic underline | bullist numlist | link blockquote emoticons charmap codesample | preview',
    # 'codesample_languages': [
    #     {'text': 'C-like', 'value': 'clike'},
    #     {'text': 'C++', 'value': 'cpp'},
    #     {'text': 'Makefile', 'value': 'makefile'},
    #     {'text': 'Python', 'value': 'python'},
    #     {'text': 'Django/Jinja2', 'value': 'django'},
    #     {'text': 'Haskell', 'value': 'haskell'},
    #     {'text': 'SQL', 'value': 'sql'},
    #     {'text': 'JSON+JSONP', 'value': 'json'},
    #     {'text': 'HTML/XML', 'value': 'html'},
    #     {'text': 'CSS', 'value': 'css'},
    #     {'text': 'JavaScript', 'value': 'javascript'},
    #     {'text': 'Diff', 'value': 'diff'},
    #     {'text': 'Docker', 'value': 'docker'},
    #     {'text': 'Git', 'value': 'git'},
    #     {'text': 'Markdown', 'value': 'markdown'},
    #     {'text': 'LaTeX', 'value': 'latex'},
    #     {'text': 'Arduino', 'value': 'arduino'},
    # ]
}


# Email settings SMTP:

EMAIL_HOST = 'localhost'
EMAIL_PORT = 1025

# Email for debug:
# EMAIL_HOST = 'localhost'
# EMAIL_PORT = 1025
# #use:
# python -m smtpd -n -c DebuggingServer localhost:1025