# Generated by Django 2.0.9 on 2018-12-17 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dracoin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='content',
            new_name='title',
        ),
    ]
