# Generated by Django 2.0.9 on 2018-12-28 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dracoin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='previous',
        ),
    ]
