# Generated by Django 2.0.9 on 2018-12-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dracoin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
