# Generated by Django 2.0.9 on 2019-01-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dracoin', '0002_auto_20181228_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
