# Generated by Django 2.0.9 on 2018-12-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dracoin', '0002_auto_20181217_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='pictures'),
        ),
    ]
