# Generated by Django 2.0.9 on 2018-12-17 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dracoin', '0003_auto_20181217_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='autor',
            new_name='author',
        ),
    ]
