# Generated by Django 2.0.9 on 2018-12-19 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dracoin', '0004_auto_20181217_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('content', models.TextField(max_length=500)),
                ('previous', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dracoin.Comment')),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dracoin.Article')),
            ],
        ),
    ]
