# Generated by Django 2.0.9 on 2018-12-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dracoin', '0004_tag_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='posts',
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='dracoin.Tag'),
        ),
    ]
