# Generated by Django 2.0.9 on 2019-01-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dracoin', '0004_auto_20190102_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='pictures'),
        ),
    ]
