# Generated by Django 2.0.9 on 2019-01-03 14:01

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('dracoin', '0005_auto_20190102_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=tinymce.models.HTMLField(blank=True, db_index=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=tinymce.models.HTMLField(db_index=True, max_length=500),
        ),
    ]
