# Generated by Django 2.0.9 on 2018-12-19 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dracoin', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='previous',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dracoin.Comment'),
        ),
    ]
