# Generated by Django 2.0.9 on 2018-12-19 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dracoin', '0007_auto_20181219_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='previous',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dracoin.Comment'),
        ),
    ]
